
exports.codes = {
    UNKNOWN: 'UNKNOWN',
    ACCESS_DENIED: 'ACCESS_DENIED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    CLAIMS_EXPIRED: 'SESSION_EXPIRED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    INVALID_IP: 'INVALID_DEVICE',
    INVALID_DEVICE: 'INVALID_DEVICE',
    METHOD_NOT_SUPPORTED: 'METHOD_NOT_SUPPORTED',
    INVALID_KEY: 'INVALID_STRING'
}

exports.messages = {
    UNKNOWN: 'Internal Server Error',
    ACCESS_DENIED: 'Insufficient Permission',
    CLAIMS_EXPIRED: 'SESSION_EXPIRED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    INVALID_IP: 'INVALID_DEVICE',
    INVALID_DEVICE: 'INVALID_DEVICE',
    METHOD_NOT_SUPPORTED: 'METHOD_NOT_SUPPORTED'
}

exports.status = {
    UNKNOWN: 500,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    BAD_REQUEST: 400,
    ACCESS_DENIED: 400,
    INVALID_TOKEN: 401,
    INVALID_CLAIMS: 403,
    CLAIMS_EXPIRED: 403,
    SESSION_EXPIRED: 403,
    INVALID_IP: 403,
    INVALID_DEVICE: 403,
    METHOD_NOT_SUPPORTED: 405
}
